### ISSUE TITLE
Grouping

### ISSUE THREAD

**Issue by sm2017** [hackolade/plugins#1]
Sorry, I know here is not good place but I don't find other way to contact you

I am using hackolade to model couchbase database , I have a bucket and many document kind and relation ship

I want to group some documents and there is no option in hackolade, Grouping with custom background color can help us understand model easily and when we distribute orthogonally it can keep group and place nearby

**Comment by pdesmarets** [comment]
Hello,

You may always send an email to support@hackolade.com 

We don't have the feature you describe, but it is seems interesting for any large model.  We will add this story to our backlog.

**Comment by pdesmarets** [comment]
A new feature called "ER Diagram Views" was introduced in Jan 2021 to support the use case you requested.  You can get more info following this [link](https://hackolade.com/help/EntityboxesinERdiagram.html#ER%20Diagram%20Views)

Apologies for the late notification.

**Comment by sm2017** [comment]
@pdesmarets Thank you very much
