### ISSUE TITLE
Avro Schema error when using non-required on RECORD types 

### ISSUE THREAD

**Issue by samuelramos** [hackolade/plugins#5]
Hi, 

When making a record non-required and setting the default value to null, the AVSC is not corrrectly generated.

![null-records-1](https://github.com/hackolade/plugins/assets/1119136/a3ad0c54-5b5b-47f0-b573-645373dd2395)
![null-records-2](https://github.com/hackolade/plugins/assets/1119136/e7e55eb1-79d3-41d7-96ca-bc2611d28ee9)

Additionally, not sure if somehow related, Choice fields (allOf, anyOf, oneOf) are not so straight forward to use

![anyOf-1](https://github.com/hackolade/plugins/assets/1119136/0fc7e131-621a-420b-9287-2439899e0007)
![anyOf-2](https://github.com/hackolade/plugins/assets/1119136/a284298e-426b-4183-aebc-8dbf7a884ee7)

Avro plugin version: 0.1.140
Hackolade version: 7.4.8

**Comment by pdesmarets** [comment]
You should really open a ticket with support@hackolade.com 

Please also provide your model so we can do proper investigations.  Best regards,

**Comment by pdesmarets** [comment]
In any case, the construction of your first example, creating a null default for your Business record is not the proper construction for a union type for a complex data type.  Please refer to this section of the documentation on how to properly construct this structure: https://hackolade.com/help/Avroschema.html#Complex%20types

Regarding your second question of choices, this is a well documented feature taken from [JSON Schema composition](https://json-schema.org/understanding-json-schema/reference/combining): "To validate against `oneOf`, the given data must be valid against exactly one of the given subschemas.".
